/*
 * generated by Xtext
 */
package org.ameba.lea.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CatalogDslUiModule extends org.ameba.lea.dsl.ui.AbstractCatalogDslUiModule {
	public CatalogDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
