/*
 * generated by Xtext
 */
package org.ameba.lea.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CatalogDslRuntimeModule extends org.ameba.lea.dsl.AbstractCatalogDslRuntimeModule {

}
