/*
 * generated by Xtext
 */
package org.ameba.lea.dsl.ui.contentassist

import org.ameba.lea.dsl.ui.contentassist.AbstractCatalogDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class CatalogDslProposalProvider extends AbstractCatalogDslProposalProvider {
}
